version: "3.8"

services:
  ocrpoc:
    build: .
    hostname: ocrpoc
    container_name: ocrpoc
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      ocr_app_net:
        ipv4_address: 172.82.1.2

networks:
  ocr_app_net:
    ipam:
      config:
        - subnet: 172.82.1.0/24
